version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cop_registros
      POSTGRES_USER: cop_user
      POSTGRES_PASSWORD: cop_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cop_user -d cop_registros"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicación web
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://cop_user:cop_password@db:5432/cop_registros
      SECRET_KEY: desarrollo-secret-key-cambiar-en-produccion
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      DEBUG: true
      ALLOWED_ORIGINS: "*"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend

volumes:
  postgres_data:
